---
# tasks file for hdp25.post-installation

- name: disable selinux
  shell: sed -i 's/SELINUX=enforcing/SELINUX=disabled/g' /etc/selinux/config /etc/selinux/config

- name: restart machine
  shell: sleep 2 && shutdown -r now "Ansible updates triggered"
  async: 1
  poll: 0
  sudo: true
  ignore_errors: true

- name: waiting for server to come back
  local_action: wait_for host={{item.url}} state=started delay=30 timeout=60
  sudo: false
  with_items:
  - { url: 10.14.90.66 }
  - { url: 10.14.90.67 }
  - { url: 10.14.90.68 }

- name: copy hosts file for multiple workers
  lineinfile: 
     dest: /etc/hosts 
     regexp: "^10.14.90."
     line: "{{ lookup('file', 'files/hosts.sample') }}"

- name: copy ssh public key
  authorized_key: user=root key="{{ item }}"
  with_file:
    - "{{ public_key }}"

- name: copy ssh private to server
  copy: src={{ private_key }} dest=/root/.ssh/id_rsa mode=0600

