---
# tasks file for hdp25.install-ambari

- name: install ambari-server
  shell: yum -y install ambari-server
  
- name: Ensure ambari-server is stopped
  service: name=ambari-server state=stopped

- name: setup ambari-server
  shell: ambari-server setup -s -j {{ java_home }}

- name: start ambari-server
  service: name=ambari-server state=restarted enabled=yes

- name: check if ambari-server is up
  wait_for: port=8080 delay=10

- name: copy ssh private to server
  copy: src={{ private_key }} dest=/root/.ssh/id_rsa mode=0600
